<a href="https://colab.research.google.com/github/Jeyakumar-M/Learnings/blob/main/DeepLearning/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors
tensors - multi dimentional numerical objects
# Creating Tensors

In [ ]:
# we can create tensors using torch.tensor()
# single value is known as scaler
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
scalar.ndim

0

In [ ]:
# represents the normal integer value
scalar.item()

5

In [ ]:
# vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [2]:
# Matrix
matrix = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
matrix.shape

torch.Size([3, 3])

In [4]:
matrix.ndim

2

In [5]:
matrix[1]

tensor([4, 5, 6])

In [6]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,0]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 0]]])

In [7]:
TENSOR.shape

torch.Size([1, 3, 3])

In [8]:
TENSOR.ndim

3

In [11]:
TENSOR[0][0]

tensor([1, 2, 3])

In [15]:
TENSOR1 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                        [[2,3,4],[5,6,7],[8,9,0]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[2, 3, 4],
         [5, 6, 7],
         [8, 9, 0]]])

In [16]:
TENSOR1.shape

torch.Size([2, 3, 3])

In [17]:
TENSOR1.ndim

3

In [23]:
TENSOR1[1][0][1]

tensor(3)

## Random Tensors

The thing why we need random tensors is many neural networks learns with tensors full of random numbers.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [24]:
# to create a random tensor of size(3,3)
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.4332, 0.5881, 0.4528],
        [0.4887, 0.5225, 0.3095],
        [0.4706, 0.9388, 0.8648]])

In [25]:
rand_tensor = torch.rand(5,5,5)
rand_tensor

tensor([[[0.0453, 0.2699, 0.9944, 0.4020, 0.2978],
         [0.6314, 0.9492, 0.1711, 0.8930, 0.4773],
         [0.7220, 0.0354, 0.5601, 0.7552, 0.0736],
         [0.3528, 0.9262, 0.5396, 0.9220, 0.0473],
         [0.9628, 0.3481, 0.7733, 0.0256, 0.3944]],

        [[0.5615, 0.0924, 0.7252, 0.7588, 0.6852],
         [0.6299, 0.9559, 0.2746, 0.5524, 0.1053],
         [0.2321, 0.7987, 0.2874, 0.8829, 0.2682],
         [0.6354, 0.8883, 0.1866, 0.4468, 0.5713],
         [0.7767, 0.0605, 0.2170, 0.6862, 0.9124]],

        [[0.1099, 0.3090, 0.6197, 0.9133, 0.7953],
         [0.3714, 0.6502, 0.9888, 0.2721, 0.9915],
         [0.2516, 0.2876, 0.3053, 0.7816, 0.2130],
         [0.4749, 0.3775, 0.2236, 0.3020, 0.5756],
         [0.8309, 0.6070, 0.1766, 0.5378, 0.3437]],

        [[0.6737, 0.9131, 0.4980, 0.8451, 0.4017],
         [0.4584, 0.8124, 0.6849, 0.6740, 0.0268],
         [0.5902, 0.5547, 0.0060, 0.2896, 0.5130],
         [0.2743, 0.8551, 0.8446, 0.3942, 0.2375],
         [0.3591, 0.1257,

In [26]:
rand_tensor.shape

torch.Size([5, 5, 5])

In [28]:
# to create a tensor which has similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
random_image_size_tensor[:2]

tensor([[[0.7075, 0.0664, 0.2410],
         [0.1487, 0.6459, 0.2021],
         [0.0575, 0.5170, 0.9599],
         ...,
         [0.6228, 0.1344, 0.1231],
         [0.5356, 0.4020, 0.9970],
         [0.8234, 0.6750, 0.1802]],

        [[0.3350, 0.0207, 0.2667],
         [0.3804, 0.5202, 0.4795],
         [0.3642, 0.1032, 0.5504],
         ...,
         [0.7041, 0.7818, 0.7376],
         [0.7014, 0.4641, 0.0352],
         [0.6823, 0.4729, 0.3605]]])

### Zeros and Ones

In [31]:
# to create a tensor with zeros
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:
# to create a tensor with ones
ones = torch.ones(4,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

## Create a range of tensors

In [34]:
torch.range(5,20)

<ipython-input-34-e9c547590717>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(5,20)


tensor([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
        19., 20.])

In [40]:
two_to_20 = torch.arange(2,20,4)

In [41]:
# to create tensors like other tensors
zeros1 = torch.zeros_like(two_to_20)
zeros1

tensor([0, 0, 0, 0, 0])

In [44]:
# default datatype of a tensor is float32

t1 = torch.tensor([1.0,2,3],
                  dtype=torch.float32,
                  device=None,
                  requires_grad=False)